name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag recipe_api_tdd:$(date +%s)
    - name: Run Tests
      run: |
        docker-compose run app sh -c "python manage.py test && flake8"
